#!/usr/bin/env python

from munin import MuninPostgresPlugin

class MuninPostgresConnectionsPlugin(MuninPostgresPlugin):
    dbname_in_args = False
    graph_title = "Postgres active connections"
    graph_args = "-l 0 --base 1000"
    graph_vlabel = "Active connections"
    graph_info = "Shows active Postgresql connections"

    @property
    def fields(self):
        c = self.cursor()
        c.execute("SHOW max_connections")
        row = c.fetchone()
        return dict(
            connections = dict(
                label = "Active connections",
                info = "Active connections",
                type = "GAUGE",
                warning = int(int(row[0]) * 0.7),
                critical = int(int(row[0]) * 0.8),
            ),
        )

    def execute(self):
        c = self.cursor()
        c.execute("SELECT COUNT(1) FROM pg_stat_activity")
        row = c.fetchone()
        print "connections.value %s" % row[0]

if __name__ == "__main__":
    MuninPostgresConnectionsPlugin().run()
