#!/usr/bin/env python

from munin.gearman import MuninGearmanPlugin

class MuninGearmanConnectionsPlugin(MuninGearmanPlugin):
    title = "Gearman Connections"
    args = "--base 1000"
    vlabel = "Connections"
    fields = (
        ('total', dict(
            label = "Total",
            type = "GAUGE",
            draw = "LINE2",
            min = "0",
        )),
        ('workers', dict(
            label = "Workers",
            type = "GAUGE",
            draw = "LINE2",
            min = "0",
        )),
        ('clients', dict(
            label = "Clients",
            type = "GAUGE",
            draw = "LINE2",
            min = "0",
        )),
    )

    def execute(self):
        workers = self.get_workers()
        print "total.value %d" % len(workers)
        print "workers.value %d" % sum(1 for x in workers if x['abilities'])
        print "clients.value %d" % sum(1 for x in workers if not x['abilities'])

if __name__ == "__main__":
    MuninGearmanConnectionsPlugin().run()
