#!/usr/bin/env python

import os
from munin.gearman import MuninGearmanPlugin

class MuninGearmanQueuesPlugin(MuninGearmanPlugin):
    title = "Gearman Queues"
    args = "--base 1000"
    vlabel = "tasks"

    _info_keys = ('total', 'running', 'workers')

    def __init__(self):
        super(MuninGearmanQueuesPlugin, self).__init__()
        self.queues = os.environ['GEARMAN_QUEUES'].split(',')

    @property
    def fields(self):
        fs = []
        for q in self.queues:
            for k in self._info_keys:
                name = "%s_%s" % (q, k)
                fs.append((name, dict(
                        label = name,
                        info = name,
                        type = "GAUGE",
                    )))
        return fs

    def execute(self):
        status = self.get_status()
        for q in self.queues:
            if q in status:
                for k in self._info_keys:
                    print "%s_%s.value %d" % (q, k, status[q][k])

if __name__ == "__main__":
    MuninGearmanQueuesPlugin().run()
