#!/usr/bin/env python

from munin.memcached import MuninMemcachedPlugin

class MuninMemcachedBytesPlugin(MuninMemcachedPlugin):
    title = "Memcached bytes read/written stats"
    args = "--base 1024"
    vlabel = "bytes per ${graph_period}"
    info = "bytes read/writter stats"
    fields = (
        ('bytes_read', dict(
            label = "bytes read",
            info = "bytes read",
            type = "DERIVE",
            min = "0",
        )),
        ('bytes_written', dict(
            label = "bytes written",
            info = "bytes written",
            type = "DERIVE",
            min = "0",
        )),
    )

if __name__ == "__main__":
    MuninMemcachedBytesPlugin().run()
