#!/usr/bin/env python

from munin.memcached import MuninMemcachedPlugin

class MuninMemcachedConnectionsPlugin(MuninMemcachedPlugin):
    graph_title = "Memcached connections stats"
    graph_args = "--base 1000"
    graph_vlabel = "Connections"
    graph_info = "connections stats"
    fields = (
        ('curr_connections', dict(
            label = "connections",
            info = "connections",
            type = "GAUGE",
        )),
    )

if __name__ == "__main__":
    MuninMemcachedConnectionsPlugin().run()
