#!/usr/bin/env python

from munin.memcached import MuninMemcachedPlugin

class MuninMemcachedCurrBytesPlugin(MuninMemcachedPlugin):
    title = "Memcached current bytes stored"
    args = "--base 1024"
    vlabel = "bytes"
    info = "bytes memory in use"
    fields = (
        ('bytes', dict(
            label = "live byte",
            info = "live bytes",
            type = "GAUGE",
        )),
    )

if __name__ == "__main__":
    MuninMemcachedCurrBytesPlugin().run()
