#!/usr/bin/env python

from munin.memcached import MuninMemcachedPlugin

class MuninMemcachedItemsPlugin(MuninMemcachedPlugin):
    title = "Memcached items stats"
    args = "--base 1000"
    vlabel = "Items"
    info = "items stats"
    fields = (
        ('total_items', dict(
            label = "items",
            info = "number new items",
            type = "COUNTER",
        )),
    )

if __name__ == "__main__":
    MuninMemcachedItemsPlugin().run()
