#!/usr/bin/env python
# -*- coding: utf-8 -*-

from munin.mongodb import MuninMongoDBPlugin

class MongoDBPageFaultsPlugin(MuninMongoDBPlugin):
    args = "-l 0 --base 1024"
    vlabel = "page faults"
    title = "MongoDB page faults"
    info = "Page faults"
    fields = (
        ('page_faults', dict(
            label = "page faults",
            info = "Page faults",
            type = "DERIVE",
            min = "0",
        )),
    )

    def execute(self):
        status = self.connection.admin.command('serverStatus')
        try:
            value = status['extra_info']['page_Faults']
        except KeyError:
            value = "U"
        print "page_faults.value", value

if __name__ == "__main__":
    MongoDBPageFaultsPlugin().run()
