#!/usr/bin/env python
# -*- coding: utf-8 -*-

from munin.mongodb import MuninMongoDBPlugin

class MongoDBFlushAvg(MuninMongoDBPlugin):
    args = "-l 0 --base 1000"
    vlabel = "seconds"
    title = "MongoDB background flushes interval"
    info = "The average time between background flushes"
    fields = (
        ('flushavg', dict(
            label = "Flush average interval",
            info = "The average time between background flushes",
            type = "GAUGE",
            min = "0",
        )),
    )

    def execute(self):
        status = self.connection.admin.command('serverStatus')
        try:
            value = float(status["backgroundFlushing"]["average_ms"])/1000
        except KeyError:
            value = "U"
        print "flushavg.value", value

if __name__ == "__main__":
    MongoDBFlushAvg().run()
