#!/usr/bin/env python

import os
import re
import urllib
from munin.nginx import MuninNginxPlugin

class MuninNginxRequestsPlugin(MuninNginxPlugin):
    title = "Nginx Requests"
    args = "--base 1000"
    vlabel = "Requests per second"
    fields = (
        ('request', dict(
            label = "req/sec",
            type = "DERIVE",
            min = "0",
            draw = "LINE2",
        )),
    )

    def execute(self):
        print "request.value %s" % self.get_status()['requests']

if __name__ == "__main__":
    MuninNginxRequestsPlugin().run()
