#!/usr/bin/env python

from munin.redis import MuninRedisPlugin

class MuninRedisTotalConnectionsPlugin(MuninRedisPlugin):
    title = "Redis total connections"
    args = "--base 1000"
    vlabel = "Connections"
    info = "total connections"
    fields = (
        ('total_connections_received', dict(
            label = "connections",
            info = "connections",
            type = "COUNTER",
        )),
    )

if __name__ == "__main__":
    MuninRedisTotalConnectionsPlugin().run()
